### ISSUE TITLE
K8090

### ISSUE THREAD

**Issue by RobNoVb** [neilhewitt/K8090-Managed-Client#1]
I used the Velleman version for connecting the K8090 card.

Now I discovered your version which is easyer to use, I want just see if it is possile to add a control to see if the card is connected or now (one problem I met with the version of Vellemn) : lost connection. or if this already exists;

Many thanks for your answer.

Robert

**Comment by neilhewitt** [comment]
There’s already a Connected property on RelayCard which reflects the state of the underlying serial port. If the card is disconnected then this will change to false. If you send a command and the card is disconnected you will get a NotConnectedException.

**Comment by RobNoVb** [comment]
Hi

Many thanks for your response.

My problem is that I am very new user of C# and I am completly lost trying to the error message in my program

I use checkbox to test each relay 1 by 1
With the version of Velleman, I lost sometime the connection and I want to be able to control it before activating but after 2 weeks l
testing all what I understand in C# with their method, procedure ...  I don't know how to do it.

if (checkBox1.Checked == true)
            {
                K8090_Card_1 contd = new K8090_Card_1();
 //               contd.EnsureConnected();
                card.SetRelayOn(0);
                errmess = K8090.ManagedClient.NotConnectedException(Message);
//                   { }
                PortConnect.Text = "Cabine 1 active";
            }

Just one little help and I'll try to do further with the rest.

Sorry to disturb and many thanks for your answer.

Robert.

________________________________
De : Neil Hewitt ***@***.***>
Envoyé : vendredi 3 mai 2024 21:41
À : neilhewitt/K8090-Managed-Client ***@***.***>
Cc : RobNoVb ***@***.***>; Author ***@***.***>
Objet : Re: [neilhewitt/K8090-Managed-Client] K8090 (Issue #1)


There’s already a Connected property on RelayCard which reflects the state of the underlying serial port. If the card is disconnected then this will change to false. If you send a command and the card is disconnected you will get a NotConnectedException.

**Comment by neilhewitt** [comment]
Can you show me some more code? Is this in a GH repo that is public? I’m not quite sure what you’re trying to do here.

**Comment by RobNoVb** [comment]
Hi

In 2000 I started with Velleman 8000 (I had to learn VB, then had to go to Velleman 8055

Now thost card don't exist anymore and obliged to go to K8090 using VB Express 2008 32bits, and I had the chance to have an old pc where I could made some development to be able to use it as the other one.

When I discoverd your version I was for me a good occasion to work on a better version of Windows but unfortunetly written in C#.
Thus obliged to start learning the language very different from the old one I used.

It's used for starting / stopping sunbeds

I took your version adding some text fields, checkfields (for testing then sunbeds one by one)

Begin of my version

using K8090.ManagedClient;

using System.Windows.Forms;
using System.Threading.Tasks;
using System.Collections.ObjectModel;
using System;
using System.IO;
using System.Text;
using Microsoft.Win32;

namespace K8090_Carte1
{
    public partial class K8090_Card_1 : Form

    {

        static string path = @"c:/protec/file/K8090/Card_2_Port";
        static string errmess = "";
    //    static string line = File.     //    This.PortConnect.Text = sr.Readline();

   I use this to pick up the port to be connected.


        RelayCard card = new RelayCard("Com3");

        public K8090_Card_1()
        {
            InitializeComponent();

            PortConnect.Text = "Com3";

            //card.Connect();


            for (int i = 0; i < 8; i++)
            {
                //              setrelay_on(i);
                card.SetRelayOn(i); // turn on relay number i
                Task.Delay(100).Wait();
                card.SetRelayOff(i); // turn the relay off again
                Task.Delay(100).Wait();
            }
        }

        private void button1_Click(object sender, System.EventArgs e)
        {
            Application.Exit();
        }

        private void checkBox1_CheckedChanged(object sender, System.EventArgs e)
        {

            //      var mc = new Class(Form1);
            if (checkBox1.Checked == true)
            {
                K8090_Card_1 contd = new K8090_Card_1();
 //               contd.EnsureConnected();
                card.SetRelayOn(0);
                errmess = K8090.ManagedClient.NotConnectedException(Message);
//                   { }
                PortConnect.Text = "Cabine 1 active";
            }
            else
            {
                card.SetRelayOff(0);
                PortConnect.Text = "Cabine 1 stoppée";
            }
        }

Many thanks for the time you spent to help me


Robert
________________________________
De : Neil Hewitt ***@***.***>
Envoyé : mercredi 15 mai 2024 23:56
À : neilhewitt/K8090-Managed-Client ***@***.***>
Cc : RobNoVb ***@***.***>; Author ***@***.***>
Objet : Re: [neilhewitt/K8090-Managed-Client] K8090 (Issue #1)


Can you show me some more code? Is this in a GH repo that is public? I’m not quite sure what you’re trying to do here.

**Comment by neilhewitt** [comment]
Hi Robert. Sorry for the delay in coming back to you. 

I'm still not sure I see the issue here, but basically whenever you use any of the APIs to communicate with the board, a check is performed to ensure that the COM port is still connected, and if it is not then a NotConnectedException is thrown. You seem to have picked up on that, but I'm really not sure what the line

`errmess = K8090.ManagedClient.NotConnectedException(Message)`;

is supposed to be doing. To catch an exception being thrown when you interact with the RelayCard, you need to wrap your calls in a try/catch block:

```
try
{
    card.SetRelayOn(0);
}
catch (NotConnectedException ex)
{
   // handle the error here however you need to
}
```

You could also pre-emptively check for the card being connected:

```
if (card.Connected)
{
    // do what you need to
}
else
{
    // handle the error condition here
}
```

This property polls the serial port directly each time, so you always get the up to date state.

If you're looking for a global error handling mechanism like VB's On Error Goto, there isn't such a thing in .NET. You could in theory use the debugger API to intercept any exceptions but you really wouldn't want to try it. 

By the way, do you realise you could write your code in VB.NET and still use my library, even in .NET 8? It wouldn't be a direct port from VB but it would be a lot simpler than a port to C#. That said, VB.NET is basically at a dead end now and won't be developed further, but it will still be supported on future versions of .NET at least for the foreseeable future.
